"""empty message

Revision ID: 61657ee59634
Revises: 792bc2246053
Create Date: 2020-11-12 10:42:57.244712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61657ee59634'
down_revision = '792bc2246053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('todo_ibfk_1', 'todo', type_='foreignkey')
    op.create_foreign_key(None, 'todo', 'user', ['user_id'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.create_foreign_key('todo_ibfk_1', 'todo', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
